"""baseline

Revision ID: 0001
Revises:
Create Date: 2026-06-24 14:47:01.923896

"""

from typing import Union
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Schemas + extension are not model-derivable; created here by hand. Idempotent
    # (IF NOT EXISTS) so order vs. the payments-svc chain on the shared DB is safe.
    # account-svc is the create-order-first chain (payments-svc FKs into auth.users).
    op.execute("CREATE SCHEMA IF NOT EXISTS auth")
    op.execute("CREATE SCHEMA IF NOT EXISTS activity")
    # pgcrypto backs the gen_random_uuid() server defaults used across tables.
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=True),
        sa.Column("keycloak_id", sa.UUID(), nullable=True),
        sa.Column("display_name", sa.String(length=100), nullable=False),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column(
            "is_email_verified",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_login_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("referral_code", sa.String(length=20), nullable=True),
        sa.Column("referred_by", sa.UUID(), nullable=True),
        sa.Column("region", sa.String(length=5), nullable=True),
        sa.ForeignKeyConstraint(
            ["referred_by"],
            ["auth.users.id"],
            name=op.f("fk_users_referred_by_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        schema="auth",
    )
    op.create_index(
        "ix_auth_users_email", "users", ["email"], unique=False, schema="auth"
    )
    op.create_index(
        op.f("ix_auth_users_keycloak_id"),
        "users",
        ["keycloak_id"],
        unique=False,
        schema="auth",
    )
    op.create_index("uq_users_email", "users", ["email"], unique=True, schema="auth")
    op.create_index(
        "uq_users_referral_code", "users", ["referral_code"], unique=True, schema="auth"
    )
    op.create_table(
        "operation_history",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("tool_id", sa.String(length=100), nullable=False),
        sa.Column("tool_label", sa.String(length=200), nullable=False),
        sa.Column("tool_type", sa.String(length=20), nullable=False),
        sa.Column("input_preview", sa.Text(), nullable=False),
        sa.Column("output_preview", sa.Text(), nullable=False),
        sa.Column("input_length", sa.Integer(), nullable=False),
        sa.Column("output_length", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.String(length=20),
            server_default=sa.text("'success'"),
            nullable=False,
        ),
        sa.Column(
            "is_deleted", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["auth.users.id"],
            name=op.f("fk_operation_history_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_operation_history")),
        schema="activity",
    )
    op.create_index(
        "ix_op_history_user_date",
        "operation_history",
        ["user_id", sa.text("created_at DESC")],
        unique=False,
        schema="activity",
        postgresql_where=sa.text("is_deleted = false"),
    )
    op.create_index(
        "ix_op_history_user_tool_date",
        "operation_history",
        ["user_id", "tool_id", sa.text("created_at DESC")],
        unique=False,
        schema="activity",
        postgresql_where=sa.text("is_deleted = false"),
    )
    op.create_index(
        "ix_operation_history_created_at",
        "operation_history",
        ["created_at"],
        unique=False,
        schema="activity",
    )
    op.create_index(
        "ix_operation_history_tool_id",
        "operation_history",
        ["tool_id"],
        unique=False,
        schema="activity",
    )
    op.create_index(
        "ix_operation_history_user_created",
        "operation_history",
        ["user_id", "created_at"],
        unique=False,
        schema="activity",
    )
    op.create_index(
        "ix_operation_history_user_id",
        "operation_history",
        ["user_id"],
        unique=False,
        schema="activity",
    )
    op.create_table(
        "shared_results",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("tool_id", sa.String(length=100), nullable=False),
        sa.Column("tool_label", sa.String(length=200), nullable=False),
        sa.Column("input_text", sa.Text(), nullable=True),
        sa.Column("output_text", sa.Text(), nullable=False),
        sa.Column(
            "view_count", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "expires_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now() + INTERVAL '30 days'"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["auth.users.id"],
            name=op.f("fk_shared_results_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_shared_results")),
        schema="activity",
    )
    op.create_index(
        "ix_shared_results_created_at",
        "shared_results",
        ["created_at"],
        unique=False,
        schema="activity",
    )
    op.create_index(
        "ix_shared_results_expires_at",
        "shared_results",
        ["expires_at"],
        unique=False,
        schema="activity",
    )
    op.create_index(
        "ix_shared_results_user_id",
        "shared_results",
        ["user_id"],
        unique=False,
        schema="activity",
    )
    op.create_table(
        "user_favorite_tools",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("tool_id", sa.String(length=100), nullable=False),
        sa.Column(
            "sort_order", sa.SmallInteger(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["auth.users.id"],
            name=op.f("fk_user_favorite_tools_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "user_id", "tool_id", name=op.f("pk_user_favorite_tools")
        ),
        schema="activity",
    )
    op.create_index(
        "ix_user_favorite_tools_user_id",
        "user_favorite_tools",
        ["user_id"],
        unique=False,
        schema="activity",
    )
    op.create_table(
        "user_gamification",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("keycloak_sub", sa.String(length=255), nullable=False),
        sa.Column("xp", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "streak_current", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("streak_last_date", sa.Date(), nullable=True),
        sa.Column("daily_quest_date", sa.Date(), nullable=True),
        sa.Column(
            "total_ops", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "total_chars", sa.BigInteger(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "achievements",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "completed_quests",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("daily_quest_id", sa.String(length=50), nullable=True),
        sa.Column(
            "daily_quest_completed",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["auth.users.id"],
            name=op.f("fk_user_gamification_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_user_gamification")),
        schema="activity",
    )
    op.create_index(
        "ix_activity_user_gamification_keycloak_sub",
        "user_gamification",
        ["keycloak_sub"],
        unique=False,
        schema="activity",
    )
    op.create_index(
        "ix_gamification_achievements_gin",
        "user_gamification",
        ["achievements"],
        unique=False,
        schema="activity",
        postgresql_using="gin",
    )
    op.create_index(
        "ix_gamification_completed_quests_gin",
        "user_gamification",
        ["completed_quests"],
        unique=False,
        schema="activity",
        postgresql_using="gin",
    )
    op.create_table(
        "user_pipelines",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["auth.users.id"],
            name=op.f("fk_user_pipelines_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_pipelines")),
        schema="activity",
    )
    op.create_index(
        "ix_user_pipelines_user_active",
        "user_pipelines",
        ["user_id"],
        unique=False,
        schema="activity",
        postgresql_where=sa.text("is_active = true"),
    )
    op.create_table(
        "user_templates",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("keycloak_sub", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("tool_id", sa.String(length=100), nullable=True),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column(
            "is_deleted", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["auth.users.id"],
            name=op.f("fk_user_templates_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_templates")),
        schema="activity",
    )
    op.create_index(
        "ix_activity_user_templates_keycloak_sub",
        "user_templates",
        ["keycloak_sub"],
        unique=False,
        schema="activity",
    )
    op.create_index(
        op.f("ix_activity_user_templates_user_id"),
        "user_templates",
        ["user_id"],
        unique=False,
        schema="activity",
    )
    op.create_index(
        "ix_user_templates_user_active",
        "user_templates",
        ["user_id", sa.text("created_at DESC")],
        unique=False,
        schema="activity",
        postgresql_where=sa.text("is_deleted = false"),
    )
    op.create_table(
        "user_tool_stats",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("tool_id", sa.String(length=100), nullable=False),
        sa.Column(
            "total_uses", sa.Integer(), server_default=sa.text("1"), nullable=False
        ),
        sa.Column(
            "last_used_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "total_uses > 0",
            name=op.f("ck_user_tool_stats_ck_user_tool_stats_uses_positive"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["auth.users.id"],
            name=op.f("fk_user_tool_stats_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", "tool_id", name=op.f("pk_user_tool_stats")),
        schema="activity",
    )
    op.create_index(
        "ix_user_tool_stats_user_uses",
        "user_tool_stats",
        ["user_id", sa.text("total_uses DESC")],
        unique=False,
        schema="activity",
    )
    op.create_table(
        "user_preferences",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "theme",
            sa.String(length=10),
            server_default=sa.text("'dark'"),
            nullable=False,
        ),
        sa.Column("persona", sa.String(length=50), nullable=True),
        sa.Column("theme_skin", sa.String(length=50), nullable=True),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["auth.users.id"],
            name=op.f("fk_user_preferences_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_user_preferences")),
        schema="auth",
    )
    op.create_table(
        "user_ui_settings",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "tool_view",
            sa.String(length=10),
            server_default=sa.text("'grid'"),
            nullable=False,
        ),
        sa.Column(
            "keybindings",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "panel_sizes",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["auth.users.id"],
            name=op.f("fk_user_ui_settings_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_user_ui_settings")),
        schema="auth",
    )
    op.create_table(
        "user_pipeline_steps",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("pipeline_id", sa.UUID(), nullable=False),
        sa.Column("step_order", sa.SmallInteger(), nullable=False),
        sa.Column("tool_id", sa.String(length=100), nullable=False),
        sa.Column("tool_label", sa.String(length=200), nullable=False),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(
            ["pipeline_id"],
            ["activity.user_pipelines.id"],
            name=op.f("fk_user_pipeline_steps_pipeline_id_user_pipelines"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_pipeline_steps")),
        schema="activity",
    )
    op.create_index(
        "ix_user_pipeline_steps_pipeline",
        "user_pipeline_steps",
        ["pipeline_id", "step_order"],
        unique=False,
        schema="activity",
    )
    op.create_index(
        "uq_pipeline_step_order",
        "user_pipeline_steps",
        ["pipeline_id", "step_order"],
        unique=True,
        schema="activity",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_pipeline_step_order", table_name="user_pipeline_steps", schema="activity"
    )
    op.drop_index(
        "ix_user_pipeline_steps_pipeline",
        table_name="user_pipeline_steps",
        schema="activity",
    )
    op.drop_table("user_pipeline_steps", schema="activity")
    op.drop_table("user_ui_settings", schema="auth")
    op.drop_table("user_preferences", schema="auth")
    op.drop_index(
        "ix_user_tool_stats_user_uses", table_name="user_tool_stats", schema="activity"
    )
    op.drop_table("user_tool_stats", schema="activity")
    op.drop_index(
        "ix_user_templates_user_active",
        table_name="user_templates",
        schema="activity",
        postgresql_where=sa.text("is_deleted = false"),
    )
    op.drop_index(
        op.f("ix_activity_user_templates_user_id"),
        table_name="user_templates",
        schema="activity",
    )
    op.drop_index(
        "ix_activity_user_templates_keycloak_sub",
        table_name="user_templates",
        schema="activity",
    )
    op.drop_table("user_templates", schema="activity")
    op.drop_index(
        "ix_user_pipelines_user_active",
        table_name="user_pipelines",
        schema="activity",
        postgresql_where=sa.text("is_active = true"),
    )
    op.drop_table("user_pipelines", schema="activity")
    op.drop_index(
        "ix_gamification_completed_quests_gin",
        table_name="user_gamification",
        schema="activity",
        postgresql_using="gin",
    )
    op.drop_index(
        "ix_gamification_achievements_gin",
        table_name="user_gamification",
        schema="activity",
        postgresql_using="gin",
    )
    op.drop_index(
        "ix_activity_user_gamification_keycloak_sub",
        table_name="user_gamification",
        schema="activity",
    )
    op.drop_table("user_gamification", schema="activity")
    op.drop_index(
        "ix_user_favorite_tools_user_id",
        table_name="user_favorite_tools",
        schema="activity",
    )
    op.drop_table("user_favorite_tools", schema="activity")
    op.drop_index(
        "ix_shared_results_user_id", table_name="shared_results", schema="activity"
    )
    op.drop_index(
        "ix_shared_results_expires_at", table_name="shared_results", schema="activity"
    )
    op.drop_index(
        "ix_shared_results_created_at", table_name="shared_results", schema="activity"
    )
    op.drop_table("shared_results", schema="activity")
    op.drop_index(
        "ix_operation_history_user_id",
        table_name="operation_history",
        schema="activity",
    )
    op.drop_index(
        "ix_operation_history_user_created",
        table_name="operation_history",
        schema="activity",
    )
    op.drop_index(
        "ix_operation_history_tool_id",
        table_name="operation_history",
        schema="activity",
    )
    op.drop_index(
        "ix_operation_history_created_at",
        table_name="operation_history",
        schema="activity",
    )
    op.drop_index(
        "ix_op_history_user_tool_date",
        table_name="operation_history",
        schema="activity",
        postgresql_where=sa.text("is_deleted = false"),
    )
    op.drop_index(
        "ix_op_history_user_date",
        table_name="operation_history",
        schema="activity",
        postgresql_where=sa.text("is_deleted = false"),
    )
    op.drop_table("operation_history", schema="activity")
    op.drop_index("uq_users_referral_code", table_name="users", schema="auth")
    op.drop_index("uq_users_email", table_name="users", schema="auth")
    op.drop_index(op.f("ix_auth_users_keycloak_id"), table_name="users", schema="auth")
    op.drop_index("ix_auth_users_email", table_name="users", schema="auth")
    op.drop_table("users", schema="auth")
    # ### end Alembic commands ###
    # Schemas are intentionally NOT dropped here: `auth` is shared with the
    # payments-svc chain (which creates auth.* usage tables and billing.*), and
    # `activity` still holds payments-svc's user_discovered_tools. Tearing those
    # down is the payments-svc downgrade's responsibility. Empty schemas are
    # harmless to leave.
